---

# tasks file for drush

- name: Create Drush folder in users home
  file:
    path: "/home/{{ drush_remote_user }}/.drush"
    state: directory
    owner: "{{ drush_remote_user }}"
    mode: 0755
    recurse: no
  remote_user: "{{ drush_remote_user }}"

- name: Clone Drush from GitHub.
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "{{ drush_install_path }}"
    version: "{{ drush_version }}"
    update: "{{ drush_keep_updated }}"
  become: true
  tags: drush

# See: https://github.com/geerlingguy/ansible-role-drush/issues/6
- name: Ensure Drush can be installed on Debian Wheezy.
  shell: >
    {{ composer_path }} update {{ drush_composer_cli_options }}
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php
  when: ansible_distribution == "Debian" and ansible_distribution_version == "7"

- name: Install Drush dependencies with Composer.
  shell: >
    {{ composer_path }} update {{ drush_composer_cli_options }}
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php
  become: true
  tags: drush


- name: Create drush symlink.
  file:
    src: "{{ drush_install_path }}/drush"
    dest: "{{ drush_path }}"
    state: link
  become: true
  tags: drush


# - name: Make sure Drush is group owned byweb admin group
#   file:

# - name: Run drush to finish setting it up.
#   command: "{{ drush_path }}"
#   register: drush_result
#   changed_when: "'Execute a drush command' not in drush_result.stdout"

- name: Run drush to finish setting it up.
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
  tags: drush

# to_do - add support for specific versions
- name: Download Drush Modules
  command: >
    drush dl {{ item }} --default-major={{ drush_default_major }} --destination=/home/{{ drush_remote_user }}/.drush/{{ item }} --yes
    creates=/home/{{ drush_remote_user }}/.drush/{{ item }}
  with_items: drush_core_modules
  when: drush_install_modules
  notify: clear drush cache
  become: false
  tags: drush


- name: Create Drush aliases folder
  file:
    path: "{{ drush_install_path }}/aliases"
    state: directory
    owner: "root"
    group: "{{ drushuser_admin_group }}"
    mode: 0755
    recurse: no
  tags: drush
  become: true

- name: Drupal | Put the drushrc file inplace
  template:
    src: drushrc.php.j2
    dest: "{{ drush_install_path }}/drushrc.php"
    owner: "root"
    group: "{{ drushuser_admin_group }}"
    mode: 0440
    backup: no
  become: true
  tags: drush